AllowExternalLinksToFail: true
CheckDoctype: false
ExternalTimeout: 60
IgnoreCanonicalBrokenLinks: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreSSLVerify: true
IgnoreAltMissing: true
IgnoreDirs:
  - download
  - manual
  - blog/2012/02/为什么我们要创造julia-simplified-chinese
