name: remark-lint check for dead links

on: [push, pull_request]

jobs:
  verify-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install remark
        run: npm install -g remark-lint remark-cli remark-lint-no-dead-urls
      - name: Verify links
        run: remark -q -u lint-no-dead-urls .
