name: Test-links

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0' 
    # Runs at 00:00 UTC on Sun

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.0'

    - name: Build
      run: hugo --gc

    - name: test-links
      run: ./bin/htmltest_mod public -c .github/.htmltest.yml
